In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,mean_squared_error,r2_score,ConfusionMatrixDisplay
from sklearn.naive_bayes import GaussianNB

In [5]:
data=pd.read_csv('iris.csv')
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [12]:
scaler=MinMaxScaler()
data['sepal.length']=scaler.fit_transform(data[['sepal.length']])
data['sepal.width']=scaler.fit_transform(data[['sepal.width']])
data['petal.length']=scaler.fit_transform(data[['petal.length']])
data['petal.width']=scaler.fit_transform(data[['petal.width']])

In [14]:
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0      0.222222     0.625000      0.067797     0.041667  Setosa
1      0.166667     0.416667      0.067797     0.041667  Setosa
2      0.111111     0.500000      0.050847     0.041667  Setosa
3      0.083333     0.458333      0.084746     0.041667  Setosa
4      0.194444     0.666667      0.067797     0.041667  Setosa

In [16]:
X=data.drop('variety',axis=1)
y=data['variety']

In [38]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [40]:
model=GaussianNB()

In [42]:
model.fit(X_train,y_train)

GaussianNB()

In [44]:
y_pred=model.predict(X_test)

In [46]:
comp=pd.DataFrame({'Actual':y_test,'Predicted':y_pred})

In [48]:
comp.head(10)

Actual   Predicted
73   Versicolor  Versicolor
18       Setosa      Setosa
118   Virginica   Virginica
78   Versicolor  Versicolor
76   Versicolor  Versicolor
31       Setosa      Setosa
64   Versicolor  Versicolor
141   Virginica   Virginica
68   Versicolor  Versicolor
82   Versicolor  Versicolor

In [50]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]


In [52]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy : ",accuracy)

Accuracy :  0.9777777777777777
